# Nama Web Nya
site_name: Himatif Utm
site_url: https://himatif-utm.github.io/penugasan/
site_description: >-
  Web ini digunakan untuk info penugasan booting & memory XIX
# Setting Repository nya
repo_name: himatif-utm/penugasan
repo_url: https://github.com/himatif-utm/penugasan/
edit_uri: ""

copyright: Copyright &copy; 2020 - Himatif UTM

nav:
  - Home:
    - Welcome: index.md
    - Peraturan: peraturan.md
    - Twibbon: twibbon.md
    - Kelompok: kelompok.md
  - Penugasan:
    - Penugasan 1: penugasan/hari-1.md
    - Penugasan 03 Oktober 2020: penugasan/penugasan-2.md
    - Penugasan 04 Oktober 2020: penugasan/penugasan-3.md
    - Penugasan 10 Oktober 2020: penugasan/penugasan-4.md
    - Penugasan 11 Oktober 2020: penugasan/penugasan-5.md

theme:
    name: null
    custom_dir: material

    # 404 page
    static_templates:
      - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    features:
      - tabs
      #- instant
    palette:
      scheme: default
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/robit1.png
    icon:
      logo: logo
